name: Pt.1 Build with GCC
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ n4.3.1-p1-ci ]
  pull_request:
    branches: [ n4.3.1-p1-ci ]

jobs:
  linux-build_with_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build FFMpeg
        shell: bash
        run: |
          bash build-with-docker.sh
      - uses: actions/upload-artifact@master
        with:
          name: ffmpeg-linux
          path: ffmpeg
  macos-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build FFMpeg
        shell: bash
        run: |
          # Make sure to use gcc-8 instead of the default gcc
          shopt -s expand_aliases
          alias gcc='gcc-8'
          bash build.sh
      - uses: actions/upload-artifact@master
        with:
          name: ffmpeg-macos
          path: ffmpeg
  # Not working with error messsage:
  #   C:\ProgramData\Chocolatey\lib\mingw\tools\install\mingw64\x86_64-w64-mingw32\bin\ar.exe: libavfilter/vsink_null: No such file or directory
  # windows-build:
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Build FFMpeg
  #       shell: bash
  #       run: |
  #         bash build.sh
